### PR TITLE
Restricted collection first implementation

### PR DESCRIPTION
**Pull request by romalytvynenko**
First restricted collection implementation. This collection is able to add item ids to collection and check that collection can add new items.

Checking that item allowed is doing by function that we pass to this collection. This function accept two arguments: all items and item that we checking. So inside this method we can strict adding item by wide range of filters, for example:

- all items count
- some internal item property

### CODE REVIEW

**Comment by XedinUnknown** [comment]
@romalytvynenko, forgot to tell you of this convention:
For all new entities, such as classes, methods, functions, tests etc, add the [`@since`](http://usejsdoc.org/tags-since.html) tag, [like this](https://github.com/Dhii/invoker-abstract/blob/task/initial-classes/src/ArgsAwareTrait.php#L18).

**Comment by romalytvynenko** [comment]
@XedinUnknown, got it. Can you please explain me logic behind this approach with `@since`?

**Comment by XedinUnknown** [comment]
The `@since` tag documents the version, at which an entity was introduced. Before the release, we search-and-replace all `[*next-version*]` occurrences with the new version number. This is very helpful, because you cannot know the number of the next version until just before its release.

**Comment by romalytvynenko** [comment]
I'm thinking about logic behind adding new item, if it is not allowed. As we discuss earlier, collection can behave in different ways, if item is not allowed:
- throw error
- add item to collection's start
- etc

What do you think, how we should deal with this?

**Comment by XedinUnknown** [comment]
I would probably try extending the array collection into a `LimitedCollection` or something. This new class would accept a number that represents the max amount of items to add, and a constant that represents what to do when overflowing.

**Comment by romalytvynenko** [comment]
And inside this collection we will hold logic for dealing with overflow depending on some passed value, yes?

**Comment by XedinUnknown** [comment]
I imagine so, since to do that we would have to probably modify the `_addItem()` method.

**Comment by romalytvynenko** [comment]
Okay, good. What about this restricted collection?

**Comment by XedinUnknown** [comment]
What about it? If you're asking whether I will merge this PR, then "no", because many functions are still missing the `@since` tags and `@return` and `@param` documentation.

**Comment by romalytvynenko** [comment]
I'm asking about purpose of this collection. If we will have some`LimitedCollection`, do we need this collection? Maybe we should add logic for overflow processing to this collection?

**Comment by XedinUnknown** [comment]
SRP, my friend.

**Comment by romalytvynenko** [comment]
So, our `paged` component will work on top of the `LimitedCollection`?

**Comment by XedinUnknown** [comment]
I guess so. What do you think about this?

**Comment by romalytvynenko** [comment]
It feels right

**Comment by XedinUnknown** [comment]
Go ahead.

**Comment by romalytvynenko** [comment]
So, should finish this PR and create new one for the `LimitedCollection`, yes?

**Comment by XedinUnknown** [comment]
That would be the most structured way, IMHO

**Comment by romalytvynenko** [comment]
I've add `since` for whole class, not for every method. Because if class since some version, this means that every method in this class is also from that version

**Comment by XedinUnknown** [comment]
Add for every method. When you release, and then add another method, you will have no way of telling where the methods came from. I specifically said:
> For all new entities, such as classes, methods, functions, tests etc

**Comment by XedinUnknown** [comment]
Missing constructor param docs, and also `@since` tag for some `describe()` and `it()` calls.

**Pull request merged**
